### ISSUE TITLE
socket connection refused

### ISSUE THREAD

**Issue by aznarepse** [tekmaven/nClam#37]
I am trying to scan a byte[] using `var scanResult = await clamClient.SendAndScanFileAsync(streamedFileContent);` but keep having a socket exception every time.
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (111): Connection refused [::ffff:172.21.0.2]:3310
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at nClam.ClamClient.ExecuteClamCommandAsync(String command, CancellationToken cancellationToken, Func`3 additionalCommand)
   at nClam.ClamClient.SendAndScanFileAsync(Byte[] fileData, CancellationToken cancellationToken)
```
If I connect to clamd at [::ffff:172.21.0.2]:3310 with telnet, everything works fine.

The project is .NET Core running in Linux against a clamd in Linux as well.

Any suggestions?

**Comment by bguidinger** [comment]
I ran into this exact same issue.  The problem is that the empty `TcpClient` constructor assumes an `AddressFamily.Unknown`.  When this happens and it tries to resolve the IP, it ends up converting it to the IPv6 format.  If you change [this](https://github.com/tekmaven/nClam/blob/6918c3caf516257aac7f242cc1adb4a7267e28ae/nClam/ClamClient.cs#L59) line to the following, it will work:

`var clam = new TcpClient(AddressFamily.InterNetwork);`

Unfortunately, it doesn't look like this repo is maintained anymore, so you'll have to clone it and make the change locally.

**Comment by aznarepse** [comment]
Thank you for the help.
I actually changed to another little lib (https://www.nuget.org/packages/ClamNet.Client/). A bit more basic but does the job.

**Comment by martinkearn** [comment]
I'm having this issue as well. I think it is related to this: https://github.com/MicrosoftDocs/azure-docs/issues/45991 as I'm trying to access the Clam server from an App Service in an Azure VNET.

**Comment by martinkearn** [comment]
The suggested fix from @bguidinger (`var clam = new TcpClient(AddressFamily.InterNetwork);`) works for me. 

It solves a problem when using the package in a Azure App Service inside a VNET.
