### ISSUE TITLE
MaxStreamSize

### ISSUE THREAD

**Issue by andriy-tsvikla** [tekmaven/nClam#59]
MaxStreamSize = 26214400; //25mb
This is from client constructor. Is there a reason for this value to exist?
Because of this value i could not process file with properly configured clamd service. I was thinking that clamd configuration was enough.

**Comment by awoehler** [comment]
My thinking was that to be able to limit the file before it unnecessarily moved further down the processing pipe.

**Comment by andriy-tsvikla** [comment]
Theoretically if you want to limit something you can limit it yourself. My issue here is that i build system from 2 components that i cant debug properly and then get this unnecessary option that blocks my request. My point that it needs to be removed if possible. But its up to library creator.`

**Comment by JorgoP56746** [comment]
Is there an option to incread the `MaxStreamSize`?
When I try to process larger file, I get the following exception:

```
System.InvalidOperationException:
Could not read response: 
nClam.MaxStreamSizeExceededException: 
The maximum stream size of 26214400 bytes has been exceeded{color}.
at nClam.ClamClient.SendStreamFileChunksAsync(Stream sourceStream, Stream clamStream, CancellationToken cancellationToken)
at nClam.ClamClient.ExecuteClamCommandAsync(String command, CancellationToken cancellationToken, Func`3 additionalCommand)
at nClam.ClamClient.SendAndScanFileAsync(Stream sourceStream, CancellationToken cancellationToken)
at ClamAvScanner.Services.ClamAvService.ScanAsync(String fileName, Stream file) 
```

I changed the value for `PCREMaxFileSize` In clamd.conf , but this does not fix the issue.
Also tried to set `PCMEMaxStreamSize`, but it doesn't change the behaviour.
